In [1]:
pip install numpy -q -upgrade


Usage:   
  /opt/anaconda3/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /opt/anaconda3/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /opt/anaconda3/bin/python -m pip install [options] [-e] <vcs project url> ...
  /opt/anaconda3/bin/python -m pip install [options] [-e] <local project path> ...
  /opt/anaconda3/bin/python -m pip install [options] <archive url/path> ...

no such option: -u
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5])

In [5]:
print("배열의 자료형:", array.dtype)

배열의 자료형: int64


In [6]:
matrix = np.array([[1,2,3], [4,5,6]])
print('2차원 배열\n', matrix)

2차원 배열
 [[1 2 3]
 [4 5 6]]


In [7]:
print('배열의 크기', matrix.size)
print('배열의 형태', matrix.shape)
print('배열의 차원', matrix.ndim)


배열의 크기 6
배열의 형태 (2, 3)
배열의 차원 2


In [9]:
print('배열의 합', np.sum(matrix))
print('배열의 평균', np.mean(matrix))

print('배열의 최대값', np.max(matrix))
print('배열의 최소값', np.min(matrix))

배열의 합 21
배열의 평균 3.5
배열의 최대값 6
배열의 최소값 1


In [10]:
transposed = matrix.T
print('전치된 배열\n', transposed)

전치된 배열
 [[1 4]
 [2 5]
 [3 6]]


In [12]:
age = 30
print('나이는 ' + str(age) + '살입니다.')

나이는 30살입니다.


In [13]:
print('apple', 'banana', 'cherry', sep=',')

apple,banana,cherry


In [15]:
print('Hello', end=' ')
print('World!')

Hello World!


In [17]:
name = 'Alice'
age = 25
print(f'이름: {name}, 나이: {age}')

이름: Alice, 나이: 25


In [19]:
# 줄 바꿈
print(f'첫 번째 줄\n두 번째 줄')

첫 번째 줄
두 번째 줄


In [20]:
print('이름\t나이')
print('Alice\t25')

이름	나이
Alice	25


In [27]:
x = 10
y = 20
print('x 깂:', x)
print('y 값:', y)

result = x + y
print('결과:', result)

name = 'Charlie'
age = 28
hobby = 'reading'

print('이름:', name, '나이:', age, '취미:', hobby)
print(f'이름: {name}, 나이: {age}, 취미: {hobby}')
print('이름: {}, 나이: {}, 취미: {}'.format(name, age, hobby))

x 깂: 10
y 값: 20
결과: 30
이름: Charlie 나이: 28 취미: reading
이름: Charlie, 나이: 28, 취미: reading
이름: Charlie, 나이: 28, 취미: reading


In [28]:
import pandas as pd

In [30]:
data = [10, 20, 30, 40]
series = pd.Series(data)
print('Series:\n', series)

Series:
 0    10
1    20
2    30
3    40
dtype: int64


In [32]:
print('첫 번째 값:', series[0])

첫 번째 값: 10


In [ ]:
data = [
    '이름'